[package]
name = "kip"
version = "0.1.0"
authors = ["Ryan Ciehanski <ryan@ciehanski.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2.3.1"
dialoguer = "0.6.2"
structopt = "0.3.14"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.53"
uuid = { version = "0.8", features = ["serde", "v4"] }
rand = "0.7.3"
aead = "0.3.0"
chacha20poly1305 = "0.5.0"
sha3 = "0.8.2"
rusoto_core = "0.43.0"
rusoto_s3 = "0.43.0"
tokio = "0.2.21"
futures = "0.3.5"
colored = "1.9.3"
prettytable-rs = "0.8.0"
# directories = "2.0.2"

[[bin]]
name = "kip"
path = "src/main.rs"
