[package]
name = "kip"
version = "0.1.0"
authors = ["Ryan Ciehanski <ryan@ciehanski.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2.3.1"
dialoguer = "0.6"
structopt = "0.3.14"
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
rand = "0.7.3"
aead = "0.3.2"
chacha20poly1305 = "0.5.0"
sha3 = "0.9.1"
rusoto_core = "0.44.0"
rusoto_s3 = "0.44.0"
tokio = "0.2.21"
colored = "2.0"
prettytable-rs = "0.8"
fastcdc = "1.0.4"
crypto-hash = "0.3.4"
pretty-bytes = "0.2.2"
rust-argon2 = "0.8.2"
directories = "3.0.1"
humantime = "2.0.1"

[lib]
name = "kip"
path = "src/lib.rs"

[[bin]]
name = "kip"
path = "src/bin/kip.rs"
